# -*- coding: utf-8 -*-
"""Conheça o Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

# Desenvolvimento de Software com Formação BackEnd

### Python com Django- Campus Samambaia (2º ciclo)

#### Aula do dia 28/05/2026

#### Tuplas (Tuple)
"""

produtos = [
    (1001, "Caneta", 1.50),
    (1002, "Caderno", 12.00),
    (1003, "Mochila", 75.90),
]

codigo_busca = 1001

for produto in produtos:
    codigo, nome, preco = produto
    if codigo == codigo_busca:
        print(f"Produto encontrado: {nome} - R$ {preco:.2f}")
        break
else:
    print("Produto não encontrado.")

alunos = [("Ana", 8.5), ("Bruno", 7.0), ("Carla", 9.3)]

print(alunos)

for i in alunos:
    print(i)

for i, x, z in alunos:
  print(f"{x} : {i} : {z}")

alunos = [("Ana", 8.5), ("Bruno", 7.0), ("Carla", 9.3)]

print(alunos)

for nome, nota in alunos:
    print(f"{nome} tirou nota {nota}")

ponto = (3, 4)
x, y = ponto
print(x)  # 3
print(y)  # 4

# Tuplas são estruturas de dados muito parecidas com listas,
# mas com uma diferença importante: são imutáveis.
# Isso significa que, uma vez criada, você não pode modificar
# os elementos da tupla (não pode adicionar, remover ou alterar valores);

# São usadas para armazenar coleções de dados que devem permanecer imutáveis,
# garantindo a integridade dessas informações.

# Elas são ideais para representar valores fixos, como coordenadas ou configurações,
# além de facilitar o retorno de múltiplos valores em funções.

# Por serem imutáveis, tuplas podem ser usadas como chaves em dicionários ou elementos
# em conjuntos, algo que listas não permitem. Além disso, tuplas oferecem melhor
# desempenho e menor consumo de memória em comparação às listas, tornando-as uma
# escolha eficiente para dados constantes.

cores = ("vermelho", "verde", "azul")
print(cores[0])  # vermelho

tarefas = []

tarefas.append("Estudar Python")
tarefas.append("Fazer exercícios")
tarefas.append("Ler documentação")

print("Tarefas iniciais:")
print(tarefas)

tarefas.insert(0, "Tomar café")

tarefas.remove("Fazer exercícios")

print("\nTarefas após alterações:")
for i in range(len(tarefas)):
    print(f"{i + 1}. {tarefas[i]}")

tarefas = []

tarefas.append("Estudar Python")
tarefas.append("Fazer exercícios")
tarefas.append("Ler documentação")

print("Tarefas iniciais:")
print(tarefas)

tarefas.insert(0, "Tomar café")

print("\nTarefas após alterações:")
for i in range(len(tarefas)):
    print(f"{i + 1}. {tarefas[i]}")

nomes = ["Ana", "Bruno", "Carla"]
for nome in nomes:
    print("Olá", nome)

tarefas.sort()
print("\nTarefas em ordem alfabética:")
print(tarefas)

tarefas.reverse()
print("\nTarefas em ordem reversa:")
print(tarefas)

ultima = tarefas.pop()
print(f"\nÚltima tarefa removida: {ultima}")

print(f"\nNúmero de tarefas restantes: {len(tarefas)}")

tarefas = []

tarefas.append("Estudar Python")
tarefas.append("Fazer exercícios")
tarefas.append("Ler documentação")

print("Tarefas iniciais:")
print(tarefas)

tarefas.insert(0, "Tomar café")

tarefas.remove("Fazer exercícios")

print("\nTarefas após alterações:")
for i in range(len(tarefas)):
    print(f"{i + 1}. {tarefas[i]}")

frutas = ["maçã","banana", "laranja"]
print(len(frutas))  # 3

letras = ["c","a","b"]
letras.reverse()
print(letras) #['b', 'a', 'c']

numeros = [3,1,2,4]
numeros.sort()
print(numeros) #[1, 2, 3, 4]

frutas = ["maçã","banana", "laranja"]
frutas.remove("banana")
print(frutas)   # ['maçã', 'laranja']

frutas = ["banana", "laranja"]
frutas.insert(0, "maçã") # índice 0
print(frutas)   # ['maçã', 'banana', 'laranja']

frutas = ["maçã", "banana", "laranja"]
ultima = frutas.pop()
print(ultima)   # 'laranja'
print(frutas)   #  ['maçã', 'banana']

frutas.pop(0)   # Remove "maçã" índice 0
print(frutas)   # ['banana']

# Listas (List) [ ]
frutas = ["maçã", "banana"]
frutas.append("uva")
print(frutas) #  ['maçã', 'banana', 'uva']

# len(): Retorna o tamanho da lista (quantidade de elementos).
numeros=[3,4,5,6,24,9,9]
print(numeros)
numeros.reverse()
print(numeros)
numeros.sort()
print(numeros)
numeros.sort(reverse=True)
print(len(numeros))



lista=["a", "b", "c", "d", "a", "d", [1,2,3,4]]

lista.append(True) # inclui
lista.remove("a")
removido = lista.pop(4)

print(lista)
print(removido)

lista=["a", "b", "c", "d", "a", "d", [1,2,3,4]]

lista.append(True) # inclui
lista.remove("a")
removido = lista.pop(4)

print(lista)
print(removido)

# lista negativa
nomes = ["Ana", "Bruno", "Carlos", [1,2,3,4]]

# mostra só os numeros
print(nomes[3])

# mostra nomes
print(nomes[0])
print(nomes[1])
print(nomes[2])

# lista negativa
nomes = ["Ana", "Bruno", "Carlos"]

print(nomes[0]) # Ana
print(nomes[1]) # Bruno
print(nomes[2]) # Calor
print(nomes[-2]) # Bruno
print(nomes[-3]) # Ana

lista = ["a", "b", "c", "d"]

# Exemplo 1
print(lista)

# Exemplo 2
print(lista[0])
print(lista[1])
print(lista[2])
print(lista[3])

# Saldo inicial fictício do usuário
saldo = 1000

# Variável para armazenar a opção escolhida no menu
op = 0

# Loop principal: continua até o usuário escolher a opção 4 (sair)
while op != 4:
    print("\n------Banco------")
    print("Consultar Saldo     - 1")
    print("Sacar Dinheiro      - 2")
    print("Depositar Dinheiro  - 3")
    print("Sair                - 4\n")

    # Solicita ao usuário que escolha uma opção
    op = input("Opção: ")

    # Estrutura condicional com if/elif/else
    if op == "1":
        # Exibe o saldo formatado com duas casas decimais
        print(f"Saldo: {saldo:.2f}")

    elif op == "2":
        # Solicita valor para saque
        valor = float(input("Sacar - Valor: "))

        # Verifica se o valor é válido e se há saldo suficiente
        if valor <= saldo and valor > 0:
            saldo = saldo - valor
            print("Saque autorizado!")
        else:
            print("Saldo insuficiente ou valor inválido.")

    elif op == "3":
        # Solicita valor para depósito
        valor = float(input("Depositar - Valor: "))
        # Verifica se o valor é positivo
        if valor > 0:
            saldo = saldo + valor
            print("Depósito realizado!")
        else:
            print("Valor inválido.")

    elif op == "4":
        # Finaliza o programa
        print("Saindo!")
        op = 4

    else:
        # Caso o usuário digite uma opção inválida
        print("Opção inválida")